# v3 syntax
version: "3"

# Named volumes
volumes:
  # MySQL Data
  carro-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: carro-mysql
    volumes:
      - carro-mysql-data:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=carro
      - MYSQL_DATABASE=carro
      - MYSQL_USER=carro
      - MYSQL_PASSWORD=carro
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: carro-app
    depends_on:
      - mysql
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: carro-phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8182:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=carro
      - MYSQL_USER=carro
      - MYSQL_PASSWORD=carro
